### ISSUE TITLE
Add flag to skip invocation of matrix

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundletester#103]
Matrix is super cool, but in some scenarios I dont want to fail an entire test run just to skip the matrix magic invocation.

proposed:

```
bundletester --no-chaos
```

This would skip the automated invocation of matrix but continue to use the classic behavior of executing charm-level tests and invoking whatever is `chmod +x tests/*`

**Comment by kwmonroe** [comment]
> This would skip the automated invocation of matrix

Is this really what you want?  Matrix does 2 things:  simple deployment, and *then* chaos.  By your flag suggestion, it sounds like you only want the chaotic test skipped.  But your later text implies you want matrix skipped all together.  Explain yourself right now.

**Comment by chuckbutler** [comment]
By forcing me to wait through matrix's basic validation, you're making my test slow.

I'm already waiting for a 'basic validation' which i presume to be the 'green test' with my tests written in amulet embedded in `$CHARM/tests`. 

So our basic thought here is what?

Lets wait for the same test to run twice with two different test harneses?

Explain why i want this, right now.

**Comment by petevg** [comment]
@chuckbutler @kwmonroe This is actually one of the issues w/ the current melding of matrix and bundletester -- matrix is meant to deprecate existing "deploy" tests, but there's nothing to stop those tests from running in bundletester.

I'm almost tempted to add a "--matrix" flag to bundletester, and only run matrix when that flag is set. juju-matrix is really a standalone tool, and its inclusion in bundletester was more an artifact of the way that the cwr-ci charm is put together than anything else.

**Comment by chuckbutler** [comment]
I have a fundamental phillisophical issue with how things are today. We're trying to deprecate an other path of test writing for automation. Thats fine and fantastic, but there are several levels of introspection that matrix is not, and can not do.

In this particular example I've changed the behavior of how the kubernetes charms react to etcd scale events. And I need to validate that in the charm.

Matrix has no concept of probing /var/snap/kube-apiserver/current/args for a specific key, and then how to in turn parse that key to validate that the number of listed apiservers == the number of deployed and active apiservers.

If we intend to fully remove this behavior, I'm going to need a replacement to specify probing for things like this level of integration test.  And I shouldn't have to wait for an hour to execute a small block of code .

**Comment by kwmonroe** [comment]
@chuckbutler:

> In this particular example I've changed the behavior of how the kubernetes charms react to etcd scale events. And I need to validate that in the bundle tests (this isn't a unit test, its an integration test).

If you're into matrix, consider converting your integration tests to matrix tests and slap a `./tests/matrix.yaml` in your bundle so BT/matrix calls them.  The point of the matrix (to me, so take this with a grain of salt) is that, out-of-the-box, it gives you a generic deploy test, without having to write a `./tests/01-simple-deploy.py`.  It has the added benefit of basic chaos, which is typically  hard to write.

I do hear your objection to *same test to run twice with two different test harneses*.  To this I say scrap *your* bundle deployment test and let the matrix do it.  Use the matrix to do more than what you've written.

> Matrix has no concept of probing /var/snap/kube-apiserver/current/args for a specific key, and then how to in turn parse that key to validate that the number of listed apiservers == the number of deployed and active etcd units.

Sure, matrix doesn't know that, but a `matrix.yaml` can point to a test that does.  Let bundletester call matrix to do it's crazy things *and* your normal things.  Do it.

**Comment by chuckbutler** [comment]
This is something I can get behind. This also means we should look into dropping amulet in favor of libjuju to be the driver of these modules (which credit for this goes to @tvansteenburgh during this morning's meeting). 

I feel like that leaves our existing amulet using masses in good shape for default behavior, and devs can enable/disable as they work through the transition, and we can then focus on the future. +1

**Comment by petevg** [comment]
Merged and done.
