### ISSUE TITLE
Output is confusing when proofing from bundles

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundletester#22]
Debugging the bundletester failures on the Kubernetes bundle yielded some interesting behavior.

I added a debug print statement to charm proof so I knew the CWD of what bundletester was actively proofing during the run.

```
DEBUG:runner:call ['/usr/bin/charm-proof']
DEBUG:runner:/tmp/bundletester-cWu5tn/kubernetes-cluster
DEBUG:runner:W: kubernetes-master: charm URL should include a revision
DEBUG:runner:E: local charms not allowed for service kubernetes-master: local:trusty/kubernetes-master
DEBUG:runner:Exit Code: 200
cs:trusty/etcd-0
    charm-proof                                                            FAIL

```
The output is targeted at the etcd charm, with a failure to proof cs:trusty/etcd-0.

However, the debug line just 3 lines above it, states CWD was the kubernetes-cluster directory, therefore the failure and associated messages, are failing during proof of the bundle.

![](http://www.chanmart.com/image/cache/data/designs/design_b973e2d4-4338-11e4-8d87-008cfa12d540/design_image-500x500.png)

**Comment by tvansteenburgh** [comment]
Fixed in v0.5.5, which has been released on PyPI.
