### ISSUE TITLE
Pass setup/wait timeouts from outside (cmd line or test.yaml)

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundletester#34]
Passing in tests.yaml is preferable I think, since that'd make it easy to specify different timeouts per test. Perhaps also include global timeouts to use for all tests instead. We'll want two separate values - one for the call to Deployment.setup(), and one for the call to sentry.wait().

**Comment by cmagina** [comment]
Adding this functionality would get me past a blocking issue when running bundletester with the apache core batch processing (hadoop) bundle due to the deployment taking a very long time (slow systems).

**Comment by tvansteenburgh** [comment]
@cmagina Thanks for your input! I'll try to get to this soon.

**Comment by tvansteenburgh** [comment]
https://github.com/juju/amulet/pull/120 has cleared the way for this.

**Comment by tvansteenburgh** [comment]
If you run amulet from source, you can pass global timeouts now, like so:

    AMULET_SETUP_TIMEOUT=300 AMULET_WAIT_TIMEOUT=500 bundletester <args>

@cmagina Are global timeouts (which apply to all tests) sufficient, or do you need to be able to customize the timeout values on a per-test basis?

**Comment by cmagina** [comment]
@tvansteenburgh I actually need access to the deployment timeout. The default is 45 minutes, which hadoop seems to need more then when deploying

**Comment by tvansteenburgh** [comment]
@cmagina AMULET_SETUP_TIMEOUT is the deployment timeout.

**Comment by cmagina** [comment]
Thanks, it worked perfectly
