### ISSUE TITLE
pkg_resources.VersionConflict when running bundletester in a freshly deployed trusty instance

### ISSUE THREAD

**Issue by cmagina** [juju-solutions/bundletester#36]
I bootstrapped a juju environment (tried an Openstack and a MAAS environment) and used the bootstrap node for my bundletester host. After deploying, I installed python-pip and python-dev via apt and then used pip to install bundletester. The stack trace I get when I just run bundletester in this environment is this:

bundletester
Traceback (most recent call last):
  File "/usr/local/bin/bundletester", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (PyYAML 3.10 (/usr/lib/python2.7/dist-packages), Requirement.parse('PyYAML==3.11'))

I hit the same issue when doing this in a virtualenv setup as well.

**Comment by cmagina** [comment]
This issue is a result of pip not upgrading pyyaml or in the very least warning the user that it can't upgrade it during the bundletester install. This issue can be hit even in a virtualenv. The workaround/solution is to use --upgrade when installing bundletester.

**Comment by tvansteenburgh** [comment]
@cmagina Ahhh, thanks for following up on this - glad you figured it out!
