### ISSUE TITLE
bundletester can not use "-e" with juju 2.0

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundletester#38]
I am trying to use juju 2.0 and I am unable to run bundletester because it tries passing a "-e" to juju, and that option has changed to "-m" for model.

We should update this to work with Juju 2.x and later.

**Comment by mbruzek** [comment]
I did some research into fixing this problem but it touches many different python programs, bundletester, deployer, and jujuclient are the applications need to be changed so far. I was still unsuccessful to start bundletester after these edits, perhaps they will help someone else or provide my failing memory some support.

bundletester/tester.py:
line 32: parser.add_argument('-m', '--model', dest="environment", help="juju model to operate in")

bundletester/builder.py:
line 29: changed '-e' to '-m'

deployer/env/base.py:
line 25: changed "-e" to "-m" 

jujuclient.py:
line 211: changed '~/.juju' to '~/.local/share/juju'
line 214: Is looking for the cache.yaml in that directory and it is not found.

**Comment by bcsaller** [comment]
The CLI changes are more involved than just s/-e/-m/g. Bootstrap syntax has
changed, models as a namespace under a controller are different than
before. The tooling, including all the things you mentioned, will have to
be made aware of this. For our tools that depend on the CLI of juju this
isn't so bad, but it is more than just search/replace. For jujuclient and
in turn deployer (if we continue to maintain that) the work is more
extensive as the API to all those things have changed a bit.

**Comment by stub42** [comment]
In some ways, the changes are significant enough to want a bundletester2. For example, I want tests running in parallel sharing a controller but each process getting its own model. Making use of these features may require redefining what bundletester is and its scope.

**Comment by tvansteenburgh** [comment]
Bundletester works with juju2 now (if you have juju2-compatible deployer and jujuclient installed). juju2-specific enhancement requests can be filed as separate issues.
