### ISSUE TITLE
don't crash on DeployError

### ISSUE THREAD

**Issue by tvansteenburgh** [juju-solutions/bundletester#46]
If the initial bundle deployment fails, handle it gracefully enough that a test result is still produced. Not sure if we should even try to run any further tests in this case, or abort here?

**Comment by johnsca** [comment]
I'm leaning toward abort, since that's closest to what happens now and other tests are likely to fail if there are deployment errors (and might take a while to do so, waiting for timeouts).  But it's possible that the additional tests might give more info as to what went wrong.  Maybe.

**Comment by tvansteenburgh** [comment]
Thanks for the input. I think I've decided that aborting is the right thing to do. It is a bundle test after all. If it doesn't even deploy, no point in continuing. Certainly wouldn't want to waste time running tests for all the charms.
