### ISSUE TITLE
Don't destroy manually provisioned machines

### ISSUE THREAD

**Issue by galgalesh** [juju-solutions/bundletester#47]
Using bundletester in a manual environment. I thought `no-destroy` would stop the manually provisioned machines from being destroyed. However, the machines are still destroyed even with that flag.

1. What does `no-destroy` do exactly?
2. How can I tell bundletester to not destroy manually provisioned machines?

I'd like to use bundletester to test compatibility with our manually provisioned environment, so switching to another provider is not really an option for me.

**Comment by tvansteenburgh** [comment]
Hey @galgalesh, what version are you using? Is it latest (0.7.1)? If not, please try that - there was a recent code change around the destroy feature. Otherwise, could you please post a log of a run using the `-vl DEBUG` options and I'll try to debug. Thanks!

**Comment by galgalesh** [comment]
```ubuntu@h-tenguci:~$ bundletester -e tenguci -b /opt/tengu-charms/bundles/testbundle/bundle.yaml -l DEBUG --no-destroy
DEBUG:bundletester.utils:Updating JUJU_ENV: "" -> "tenguci"
DEBUG:root:Bootstrap environment: tenguci
DEBUG:deployer.env:Connecting to environment...
DEBUG:deployer.env:Connected to environment
DEBUG:root:deploy juju-deployer -c /opt/tengu-charms/bundles/testbundle/bundle.yaml
DEBUG:root:2016-06-09 05:52:57 Using deployment /opt/tengu-charms/bundles/testbundle/bundle.yaml
DEBUG:root:2016-06-09 05:52:57 Starting deployment of /opt/tengu-charms/bundles/testbundle/bundle.yaml
DEBUG:root:2016-06-09 05:52:58 Creating machines...
DEBUG:root:2016-06-09 05:52:58 Machine 0 already exists on environment, skipping creation
DEBUG:root:2016-06-09 05:52:58 Deploying services...
DEBUG:root:2016-06-09 05:52:58  Deploying service hauchiwa using local:trusty/hauchiwa
DEBUG:root:2016-06-09 05:53:21  Deploying service rest2jfed using local:trusty/rest2jfed
DEBUG:root:2016-06-09 06:02:25 Adding relations...
DEBUG:root:2016-06-09 06:02:27 Deployment complete in 569.37 seconds
DEBUG:deployer.env: Destroying service hauchiwa
DEBUG:deployer.env: Destroying service rest2jfed
DEBUG:deployer.env:  No unit errors found.
DEBUG:deployer.env: Terminating machines forcefully
DEBUG:deployer.env:  Terminating machine 0/lxc/3
DEBUG:deployer.env:  Terminating machine 0/lxc/4
DEBUG:deployer.env: Delta unit: hauchiwa/2 remove:started
DEBUG:deployer.env: Delta service: hauchiwa change:{u'Err': None, u'Since': u'2016-06-09T06:02:29.427215926-06:00', u'Current': u'blocked', u'Version': u'', u'Message': u'Waiting for connection to rest2jfed', u'Data': {}}
DEBUG:deployer.env: Delta service: hauchiwa remove:{u'Err': None, u'Since': u'2016-06-09T06:02:29.427215926-06:00', u'Current': u'blocked', u'Version': u'', u'Message': u'Waiting for connection to rest2jfed', u'Data': {}}
DEBUG:deployer.env: Delta machine: 0/lxc/3 change:started
DEBUG:deployer.env: Delta unit: rest2jfed/2 remove:started
DEBUG:deployer.env: Delta machine: 0/lxc/3 change:stopped
DEBUG:deployer.env: Delta service: rest2jfed remove:{u'Err': None, u'Since': None, u'Current': u'', u'Version': u'', u'Message': u'', u'Data': None}
DEBUG:deployer.env: Delta machine: 0/lxc/4 change:started
DEBUG:deployer.env: Delta machine: 0/lxc/4 change:stopped
DEBUG:deployer.env: Delta machine: 0/lxc/3 remove:stopped
DEBUG:deployer.env: Delta machine: 0/lxc/4 remove:stopped
INFO:deployer.env:  Waiting for machine termination
DEBUG:root:Waiting for services to be removed...
DEBUG:runner:call ['/usr/bin/charm-proof'] (cwd: /tmp/tmpDC1aGN/rest2jfed)
DEBUG:runner:Exit Code: 0
rest2jfed
    charm-proof                                                            PASS
DEBUG:deployer.env: Terminating machines forcefully
DEBUG:root:Waiting for services to be removed...
DEBUG:runner:call ['/usr/bin/charm-proof'] (cwd: /tmp/tmpbCOMO_/hauchiwa)
DEBUG:runner:I: Includes template icon.svg file.
DEBUG:runner:E: actions.deploy-bundle: actions/deploy-bundle is not executable
DEBUG:runner:I: config.yaml: option environment-jenv has no default value
DEBUG:runner:I: config.yaml: option bundle has no default value
DEBUG:runner:I: config.yaml: option ssh-keys has no default value
DEBUG:runner:I: config.yaml: option environment-config has no default value
DEBUG:runner:I: config.yaml: option environment-name has no default value
DEBUG:runner:Exit Code: 200
hauchiwa
    charm-proof                                                            FAIL
DEBUG:bundletester.utils:Updating JUJU_ENV: "tenguci" -> ""

------------------------------------------------------------------------------
FAIL: hauchiwa::charm-proof
[/usr/bin/charm-proof           exit 200]
I: Includes template icon.svg file.
E: actions.deploy-bundle: actions/deploy-bundle is not executable
I: config.yaml: option environment-jenv has no default value
I: config.yaml: option bundle has no default value
I: config.yaml: option ssh-keys has no default value
I: config.yaml: option environment-config has no default value
I: config.yaml: option environment-name has no default value

PASS: 1 FAIL: 1 SKIP:3 Total: 5 (0.440845 sec)
```

**Comment by tvansteenburgh** [comment]
@galgalesh Okay, it's not actually destroying, it's resetting the environment before each test. You can disable this by setting `reset: false` in tests.yaml (see https://github.com/juju-solutions/bundletester#testsyaml).

**Comment by galgalesh** [comment]
PS: I think you made a typo there. It's `-l`, not `-vl`. :)

**Comment by tvansteenburgh** [comment]
@galgalesh No, there's a -v flag also.

**Comment by galgalesh** [comment]
Alright, thanks!

Which tests.yaml should this go in? I'm a bit confused by all the possible places. A bundle can have a tests directory, but each charm can also have a tests directory. When a bundle deploys. Are the individual charm tests also run?

**Comment by tvansteenburgh** [comment]
@galgalesh You can have `tests/tests.yaml` in both charms and bundles. By default, a bundle test will also run tests for it's constituent charms, but you can override this by using `-x <charm name>` or the `excludes` key in the bundle's tests.yaml to exclude tests for one or more charms in the bundle. `-b` is only needed if you have multiple bundle yaml files in your bundle dir - it tells bundletester which bundle file to use for the test. Otherwise you can use `-t` to specify the location of the thing to be tested (a path or a uri). The default is the cwd.

**Comment by galgalesh** [comment]
Ok. I'm starting to get it.

I have a manually deployed environment with some helper charms in it to enable containers and stuff like that. I want everything a test creates to be destroyed. Stuff that isn't created by a test shouldn't be destroyed.

I think the following will solve this:

- put `reset: false` in every `tests.yaml`
- write a `teardown` script that destroys everything the test created and link to it in every `tests.yaml` file.

Is there a way to override all other `test.yaml` files?

**Comment by tvansteenburgh** [comment]
@galgalesh If the teardown script is the same for every charm, I think you can just put it in the bundle, and add the `teardown: myscript` to the bundle's tests.yaml.
